---
- name: Install Modules on ARM64 Server-05
  hosts: ARM64Server05
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
    - { role: openjdk, when: order_cpus is defined}
    - { role: zookeeper }
    - { role: solrcloud, when: solr_cpus is defined }

- name: Install Modules on ARM64 Server-06
  hosts: ARM64Server06
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
    - { role: openjdk, when: order_cpus is defined}
    - { role: zookeeper }

- name: Install Modules on ARM64 Server-07
  hosts: ARM64Server07
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
    - { role: openjdk, when: order_cpus is defined}
    - { role: zookeeper }


- name: Install Modules on ARM64 Server-08
  hosts: ARM64Server08
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo

- name: Install Modules on ARM64 Server-09
  hosts: ARM64Server09
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
    - { role: twemproxy, when: twemproxy_cpus is defined }

- name: Install Modules on ARM64 Server-10
  hosts: ARM64Server10
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
    - { role: lvs, when: lvs_cpus is defined }

- name: Install Modules on ARM64 Server-11
  hosts: ARM64Server11
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo

- name: Install Modules on ARM64 Server-12
  hosts: ARM64Server12
  remote_user: estuaryapp
  become: yes
  become_method: sudo
  roles:
    - estuaryrepo
