---
# This role is to setup solr test scripts

- name: Create Solr E-Commerce Core and Fields
  shell: "{{ workspace }}/solr_benchmark/solr_create_fields.sh {{ solr_server }} {{ solr_port }} {{ estuaryuser }}" 

- name: Download Test Data 
  get_url:
     url: "ftp://repoftp:repopushez7411@117.78.41.188/releases/3.0/otherfiles/solr_ecommerce_data.tar.gz"
     dest: "{{ workspace }}/solr_benchmark/solr_ecommerce_data.tar.gz"

- name: Extract Test Data
  shell: "tar -zxf {{ workspace }}/solr_benchmark/solr_ecommerce_data.tar.gz -C {{ workspace }}/solr_benchmark" 

- name: Load Test Data
  shell: "{{ workspace }}/solr_benchmark/solr_post_data.sh {{ solr_server }} {{ solr_data_file }} {{ solr_port }}" 

