---
# This role is to setup solr test scripts

- name: Create Solr E-Commerce Core and Fields
  shell: "{{ workspace }}/solr_benchmark/solr_create_fields.sh {{ solr_server }} {{ solr_port }} {{ estuaryuser }}" 

- name: Download Test Data 
  get_url:
     url: "{{ solr_data_url }}"
     dest: "{{ workspace }}/solr_benchmark/solr_ecommerce_data.tar.gz"

- name: Extract Test Data
  unarchive:
      src: "{{ workspace }}/solr_benchmark/solr_ecommerce_data.tar.gz"
      dest: "{{ workspace }}/solr_benchmark"
      remote_src: yes
  become: yes
  become_user: "{{ estuaryuser }}"

- name: Load Test Data
  shell: "{{ workspace }}/solr_benchmark/solr_post_data.sh {{ solr_server }} {{ solr_data_file }} {{ solr_port }}" 

